services:
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:8080
    depends_on:
      - db

  db:
    image: postgres:14.18-alpine3.21
    command: postgres -c max_connections=1000
    environment:
      - POSTGRES_DB=tg-dmp
      - POSTGRES_USER=tg-dmp
      - POSTGRES_PASSWORD=tg-dmp
